import {
  Sparkles,
  Wrench,
  Hammer,
  Scissors,
  Car,
  Home,
  Heart,
  Stethoscope,
  Paintbrush,
  Leaf,
  Camera,
  Dumbbell,
  GraduationCap,
  Scale,
  Briefcase,
  Utensils,
  Dog,
  Baby,
  Shirt,
  Plug,
  Droplet,
  Flame,
  Shield,
  Star,
  Calendar,
  Clock,
  Phone,
  Package,
  type LucideIcon,
} from "lucide-react";

/** Maps a stored service icon key (see SERVICE_ICONS) to its lucide component. */
export const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  car: Car,
  home: Home,
  heart: Heart,
  stethoscope: Stethoscope,
  paintbrush: Paintbrush,
  leaf: Leaf,
  camera: Camera,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  scale: Scale,
  briefcase: Briefcase,
  utensils: Utensils,
  dog: Dog,
  baby: Baby,
  shirt: Shirt,
  plug: Plug,
  droplet: Droplet,
  flame: Flame,
  shield: Shield,
  star: Star,
  calendar: Calendar,
  clock: Clock,
  phone: Phone,
  package: Package,
};
